apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8zno
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0032-tenant/ci1t-830-0032-app/devfile-sample-8zno@sha256:315353691bfe6cab7be8b439295cd7e6861efc1313ba4dffe37f0bda73e8cb7c
        name: my-nodejs
        resources: {}
status: {}
